title = "Europe 27"
baseURL = "https://evropa27.org"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

canonifyURLs = true


[languages]
  [languages.en]
    title = "Europe 27"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1
      
   
  [languages.sr]
    languageCode = "sr-latn"
    title = "Evropa 27"
    weight = 2
    contentDir = "content/sr"
    [[languages.sr.menu.main]]
      name = "Naslovna"
      url = "/sr/"
      weight = 1
    

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/siteimages/znak_evropa_100px.png"
  TIMEZONE = "Europe/Berlin"
  date_format = "2. January 2006"
  description = "L.: Europe 27, Orient Belgrade, public info."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  recent_posts_number = 3
  # about_style = "full_width"

# [[params.ananke_socials]]

[languages.sr.params]
  date_format = "2. Januar 2006"
 